### ISSUE TITLE
create matches for a schedule

### ISSUE THREAD

**Issue by Project-neuron** [AdamKruschwitz/FootballApp#29]

**Comment by Project-neuron** [comment]
Done when matches can be made

**Comment by AdamKruschwitz** [comment]
I'll take these cards

**Comment by AdamKruschwitz** [comment]
I worked for 2 hours on a match class and a tests for that class so that a date and time can be associated with a match. This will allow the schedule class to find all matches and report the time of each match. Later, when team rosters are implemented, we can find individual players schedules.
