### ISSUE TITLE
Add Roster

### ISSUE THREAD

**Issue by ElvinLord12** [AdamKruschwitz/FootballApp#3]
Done when team captain or organizer can add a roster to a unregistered or registered team.

**Comment by Project-neuron** [comment]
Version one complete, still requires the player class to be completed before full functionality can be built. 

30 mins to create the class

**Comment by AdamKruschwitz** [comment]
Everything looks good here, really wonderful work. I reviewed it this morning but forgot to comment, I remember there being a single issue where an assignment operator was used instead of a comparator, but that was resolved quickly.
