### ISSUE TITLE
Run League

### ISSUE THREAD

**Issue by AdamKruschwitz** [AdamKruschwitz/FootballApp#56]
Run a league with a number of teams. Each team should play each other team twice. a team gets 2 points for a win, 1 point for a tie, 0 points for a loss. Will be complete when all games can be played and we can see the final leaderboard.
Teams play one game every weekend, and their score is updated.
parent #30
parent #42
parent #8
parent #62
parent #60
parent #25

**Comment by AdamKruschwitz** [comment]
parent of #31

**Comment by Project-neuron** [comment]
parent #57

**Comment by lkpfaff** [comment]
2 hrs so far
