### ISSUE TITLE
Set league schedule

### ISSUE THREAD

**Issue by Project-neuron** [AdamKruschwitz/FootballApp#62]

**Comment by Project-neuron** [comment]
Done when a list of teams that are in the league can be set to matches by the user, basically defining a league schedule

**Comment by Project-neuron** [comment]
3 hrs

**Comment by AdamKruschwitz** [comment]
Need to be able to show league schedule Before games are played.

**Comment by Project-neuron** [comment]
Done when a league schedule string is shown where the team matchups are displayed
