### ISSUE TITLE
Enter League mode in UI

### ISSUE THREAD

**Issue by Project-neuron** [AdamKruschwitz/FootballApp#63]

**Comment by Project-neuron** [comment]
Done when upon selecting run a league mode a user is given these commands for a league: 
add a team to the league (allows a team to be added to a league)
Set league match schedule (allows the user to set a match for two teams within a league)
Run a round #number in league (runs all the matches in round 1 then round 2 until all rounds have been completed)
Get total amount of rounds in league (get the total amount of rounds still yet to be played in the league)
See leader board  (dispaly points for all teams in league)
generate tourney from the league top #number inputted by user  (will only run when the league is complete.)

**Comment by lkpfaff** [comment]
2.5 hrs

**Comment by lkpfaff** [comment]
~3hrs
